# Configuración del Servidor
server.port=${SERVER_PORT:8084}
spring.application.name=ms-reportes
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Base de datos (PostgreSQL - AWS RDS)
spring.datasource.url=jdbc:postgresql://fireforce.c1w28coqqryx.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=Fireforce
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka (se activa cuando kafka.enabled=true y Docker Kafka está corriendo)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
